# Generated by Django 4.1 on 2022-08-11 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('base_ac', models.IntegerField()),
                ('dex_bonus', models.BooleanField()),
                ('bonus_cap', models.IntegerField()),
                ('strength_requirement', models.IntegerField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('xp', models.IntegerField()),
                ('bio', models.TextField()),
                ('image_url', models.TextField()),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.armor')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.background')),
            ],
        ),
        migrations.CreateModel(
            name='CombatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('primary_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('description', models.TextField()),
                ('alignment', models.TextField()),
                ('rgb', models.TextField()),
                ('icon_url', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('damage_die', models.IntegerField()),
                ('number_of_damage_die', models.IntegerField()),
                ('image_url', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.attribute')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hit_die', models.IntegerField()),
                ('life', models.IntegerField()),
                ('will', models.IntegerField()),
                ('will_per_level', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('stamina_per_level', models.IntegerField()),
                ('devotion_points', models.IntegerField()),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
                ('armor_proficiencies', models.ManyToManyField(related_name='subclasses', to='maskedlandsapi.armortype')),
                ('combat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.combatclass')),
                ('weapon_proficiencies', models.ManyToManyField(related_name='subclasses', to='maskedlandsapi.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('devotion_level', models.IntegerField()),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('will_cost', models.TextField()),
                ('attack_range', models.IntegerField()),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.actiontype')),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.god')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('speed', models.IntegerField()),
                ('image_url', models.TextField()),
                ('primary_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterDevotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devotion_points', models.IntegerField()),
                ('devotion_level', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.character')),
                ('god', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.god')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.attribute')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='combat_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.combatclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.species'),
        ),
        migrations.AddField(
            model_name='character',
            name='subclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.subclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.weapon'),
        ),
        migrations.CreateModel(
            name='BackgroundAttributeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.attribute')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.background')),
            ],
        ),
        migrations.AddField(
            model_name='background',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.species'),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskedlandsapi.armortype'),
        ),
    ]
