# Generated by Django 4.1 on 2022-10-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maskedlandsapi', '0002_remove_character_user_player_character_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='background',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='maskedlandsapi.species'),
        ),
        migrations.AlterField(
            model_name='characterattribute',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='maskedlandsapi.character'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='combat_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='maskedlandsapi.combatclass'),
        ),
    ]
