# Generated by Django 4.1 on 2022-10-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskedlandsapi', '0003_character_base_charisma_character_base_constitution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='base_wisdom',
            new_name='base_attunement',
        ),
    ]
