# Generated by Django 4.1 on 2022-10-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskedlandsapi', '0004_rename_base_wisdom_character_base_attunement'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='escritorio_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='faelina_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='garthank_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='goge_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='moonface_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='sunface_pts',
            field=models.IntegerField(default=0),
        ),
    ]
