# Generated by Django 4.1 on 2022-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskedlandsapi', '0005_character_escritorio_pts_character_faelina_pts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_max_life',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='base_max_stamina',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='base_max_will',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='current_life',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='current_stamina',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='current_will',
            field=models.IntegerField(default=5),
        ),
    ]
