# Generated by Django 4.1 on 2022-10-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskedlandsapi', '0006_character_base_max_life_character_base_max_stamina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hit_die',
            field=models.IntegerField(default=6),
        ),
    ]
